/**
 * Imports the hand-drawn "M on the scooter" from intro-m-fit.svg (edited in Figma,
 * Illustrator, …) and writes lib/intro/mOnFace.ts, which the intro traces before the M
 * rises and squares up into the real logo.
 *
 * The drawing is in the photo's own pixels (the file's viewBox is 844 x 1500), so the
 * paths are taken as they are; only the backdrop rect is skipped. The bounding box is
 * measured here so the component can place the photo without re-measuring in the browser.
 *
 * Usage: node scripts/import-intro-m.mjs <edited.svg>
 */
import { fileURLToPath } from "node:url";
import fs from "node:fs";
import path from "node:path";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const [, , source] = process.argv;

if (!source) {
  console.error("Usage: node scripts/import-intro-m.mjs <edited.svg>");
  process.exit(1);
}

const svg = fs.readFileSync(source, "utf8");
const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"[^>]*>/g)]
  .map((m) => m[1].trim())
  // The backdrop is a full-canvas rectangle; everything else is the drawing.
  .filter((d) => !/^M\s*0?\s*844?[\s,]/.test(d) && !/^M844 0H0V1500H844V0Z$/.test(d));

if (paths.length !== 2) {
  console.error(`Expected 2 paths (the M's two halves), found ${paths.length}.`);
  process.exit(1);
}

/** Walks an absolute path (M/L/C/H/V/Z), sampling curves, to get its extent. */
function bounds(d) {
  let cur = [0, 0];
  let start = [0, 0];
  const box = { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity };
  const hit = ([x, y]) => {
    box.minX = Math.min(box.minX, x);
    box.minY = Math.min(box.minY, y);
    box.maxX = Math.max(box.maxX, x);
    box.maxY = Math.max(box.maxY, y);
  };
  for (const [, cmd, args] of d.matchAll(/([MLCHVZ])([^MLCHVZ]*)/gi)) {
    const n = (args.match(/-?\d*\.?\d+/g) ?? []).map(Number);
    const c = cmd.toUpperCase();
    if (c === "Z") {
      cur = start;
      continue;
    }
    if (c === "H") cur = [n[0], cur[1]];
    else if (c === "V") cur = [cur[0], n[0]];
    else if (c === "C") {
      for (let i = 0; i < n.length; i += 6) {
        const p = [cur, [n[i], n[i + 1]], [n[i + 2], n[i + 3]], [n[i + 4], n[i + 5]]];
        for (let t = 0; t <= 1; t += 1 / 16) {
          const u = 1 - t;
          hit([0, 1].map((k) => u ** 3 * p[0][k] + 3 * u * u * t * p[1][k] + 3 * u * t * t * p[2][k] + t ** 3 * p[3][k]));
        }
        cur = p[3];
      }
    } else {
      for (let i = 0; i < n.length; i += 2) cur = [n[i], n[i + 1]];
      if (c === "M") start = cur;
    }
    hit(cur);
  }
  return box;
}

const boxes = paths.map(bounds);
const box = boxes.reduce((a, b) => ({
  minX: Math.min(a.minX, b.minX),
  minY: Math.min(a.minY, b.minY),
  maxX: Math.max(a.maxX, b.maxX),
  maxY: Math.max(a.maxY, b.maxY),
}));
// Left half first, so it pairs with the logo's own halves.
const ordered = paths
  .map((d, i) => ({ d, mid: (boxes[i].minX + boxes[i].maxX) / 2 }))
  .sort((a, b) => a.mid - b.mid)
  .map((p) => p.d);

const out = path.join(root, "lib/intro/mOnFace.ts");
fs.writeFileSync(
  out,
  `// Generated by scripts/import-intro-m.mjs from ${path.basename(source)} — do not edit by hand.
// The M as it lies on the scooter, drawn over the blueprint in the photo's own pixels.
// Left half first. The intro traces this, then morphs it into the real logo.

export const M_ON_FACE = [
${ordered.map((d) => `  ${JSON.stringify(d)},`).join("\n")}
];

/** Its extent in photo px, for placing the photo behind the M. */
export const M_ON_FACE_BOX = { x: ${box.minX.toFixed(1)}, y: ${box.minY.toFixed(1)}, w: ${(box.maxX - box.minX).toFixed(1)}, h: ${(box.maxY - box.minY).toFixed(1)} } as const;
`,
);
console.log(`wrote ${path.relative(root, out)} — box ${box.minX.toFixed(0)},${box.minY.toFixed(0)} ${(box.maxX - box.minX).toFixed(0)}x${(box.maxY - box.minY).toFixed(0)}`);
